In [29]:
## NUMPY array and basics


# creating array using NUMPY

import numpy as np

arr = np.array([3,4,5,6,7])
print(arr)

[3 4 5 6 7]


In [30]:
print(np.__version__)

2.2.4


In [31]:
# checking number of dimension

arr = np.array([[4,5,6,3],[3,5,4,6],[4,8,9,0]])
ar = np.array([4,8,3])
print(ar, type(ar))

print(arr , arr.ndim , type(arr))

[4 8 3] <class 'numpy.ndarray'>
[[4 5 6 3]
 [3 5 4 6]
 [4 8 9 0]] 2 <class 'numpy.ndarray'>


In [32]:
#defining number of dimesion 

arr = np.array([3,4,5,6], ndmin= 2)

print(arr , arr.ndim)

[[3 4 5 6]] 2


In [37]:
# indexing 

arr = np.array([[4,5,6,3],[4,6,7,8]])

print(arr[0,3])




3


In [ ]:
#slicing 
arr = np.array([[4,5,6,3],[4,6,7,8]])

print(arr[0,1:3])
print(arr[0,1:4])


arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[5 6]
[5 6 3]
